sudo: required
language: node_js
node_js:
  - '11'
services:
  - docker
before_install:
  - 'if [ "$TRAVIS_PULL_REQUEST" = "false" ]; then bash ./build/pre-build.sh; fi'
  - yarn
script:
  - yarn test:unit
after_script:
  - yarn coveralls
after_success:
  - 'if [ "$TRAVIS_PULL_REQUEST" = "false" ]; then bash ./build/build.sh; fi'
branches:
  only:
    - master
cache:
  npm: true
  yarn: true
  directories:
    - node_modules
    - /home/travis/.nvm/
