sudo: required
language: node_js
node_js:
  - '11'
services:
  - docker
install:
  - yarn
script:
  - yarn lint
  - yarn test:unit
after_success:
  - 'if [ "$TRAVIS_BRANCH" = "master" ]; then yarn coveralls; fi'
  - bash ./build/example.sh
cache:
  npm: true
  yarn: true
  directories:
    - node_modules
branches:
  only:
    - master
    - develop
    - /^feature/.*$/
